# Generated by Django 3.2.13 on 2022-05-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='description',
        ),
    ]
