# Generated by Django 3.2.13 on 2022-05-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_rename_caption_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='placeholder'),
        ),
    ]
